# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-18 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('pno', models.IntegerField()),
                ('cf', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='sugus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=25)),
                ('about', models.TextField()),
            ],
        ),
    ]
