# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-19 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampark', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contus',
            old_name='cf',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='contus',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contus',
            old_name='pno',
            new_name='Phone_No',
        ),
        migrations.RenameField(
            model_name='sugus',
            old_name='about',
            new_name='About',
        ),
        migrations.RenameField(
            model_name='sugus',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='sugus',
            old_name='place',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='sugus',
            old_name='sname',
            new_name='Place',
        ),
        migrations.RemoveField(
            model_name='contus',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sugus',
            name='email',
        ),
        migrations.AddField(
            model_name='contus',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sugus',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
