# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('C_Id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
                ('Best_time_to_visit', models.CharField(max_length=20)),
                ('About', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=20)),
                ('About', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.Countries'),
        ),
    ]
