# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
