# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_cities_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='C_Id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
