# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_auto_20170716_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
