# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_auto_20170717_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='About',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='countries',
            name='About',
            field=models.TextField(),
        ),
    ]
