# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_auto_20170717_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
    ]
