# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_auto_20170717_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='C_About',
            new_name='About',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='C_Name',
            new_name='Name',
        ),
    ]
