# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0008_auto_20170717_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='Best_time_to_visit',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cities',
            name='Name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='countries',
            name='Location',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='countries',
            name='Name',
            field=models.TextField(max_length=20),
        ),
    ]
