# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_auto_20170717_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cities',
            name='Type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='countries',
            name='Location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='countries',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
