# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-22 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0010_auto_20170718_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Countries'),
        ),
    ]
