# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0011_countries_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='home_page.Countries'),
        ),
    ]
