# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0012_auto_20170725_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='Best_time_to_visit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cities',
            name='Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='home_page.Countries'),
        ),
    ]
